# Generated by Django 5.2 on 2025-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('time_complexity', models.CharField(max_length=50)),
                ('space_complexity', models.CharField(max_length=50)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
